server:
  port: 8080

spring:
  ai:
    bedrock:
      aws:
        region: ${BEDROCK_REGION:ap-northeast-2}
      converse:
        chat:
          options:
            model: ${BEDROCK_MODEL_ID:}
            max-tokens: ${BEDROCK_MAX_TOKENS:8096}
    chat:
      memory:
        repository:
          bedrock:
            agent-core:
              memory:
                memory-id: ${BEDROCK_MEMORY_ID:}
                actor-id: ${BEDROCK_ACTOR_ID:spring-ai}
    a2a:
      remote:
        agents:
          order-agent:
            url: ${ORDER_AGENT_URL:}
          delivery-agent:
            url: ${DELIVERY_AGENT_URL:}
          payment-agent:
            url: ${PAYMENT_AGENT_URL:}
