spring:
  config:
    activate:
      on-profile: local

server:
  port: 9003

a2a:
  agent-url: http://localhost:9003

logging:
  level:
    io.github.cokelee777: DEBUG
    org.springframework.ai: DEBUG
