server:
  port: 9003

spring:
  config:
    activate:
      on-profile: local
  ai:
    a2a:
      server:
        enabled: true
        url: http://localhost:${server.port}

logging:
  level:
    io.github.cokelee777: DEBUG
    org.springframework.ai: DEBUG
